services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - nestjs_network

networks:
  nestjs_network:
    name: nestjs_network